services:
  clickhouse:
    image: bitnami/clickhouse:latest
    container_name: clickhouse
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - clickhouse-network
    ports:
      - 8123:8123 # http
      - 9000:9000 # tcp

networks:
  clickhouse-network:
    driver: bridge
