services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    networks:
      - clickhouse-network
    ports:
      - 8123:8123 # http
      - 9100:9000 # tcp

networks:
  clickhouse-network:
    driver: bridge
